### ISSUE TITLE
App stops with an OutOfMemoryException when switching from portrait mode to landscape and back multiple times

### ISSUE THREAD

**Issue by antsher** [ksheremet/CocktailsPro#10]
2018-09-14 13:57:10.168 23199-23269/ch.sheremet.katarina.cocktailspro E/CrashlyticsCore: Failed to execute task.
    java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available
        at java.util.concurrent.FutureTask.report(FutureTask.java:94)
        at java.util.concurrent.FutureTask.get(FutureTask.java:164)
        at com.crashlytics.android.core.CrashlyticsBackgroundWorker.submitAndWait(CrashlyticsBackgroundWorker.java:43)
        at com.crashlytics.android.core.CrashlyticsController.handleUncaughtException(CrashlyticsController.java:321)
        at com.crashlytics.android.core.CrashlyticsController$6.onUncaughtException(CrashlyticsController.java:301)
        at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:42)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
     Caused by: java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available

**Comment by ksheremet** [comment]
https://android.jlelse.eu/using-glide-few-tips-to-be-a-pro-60f41e29d30a
